version: '3.9'

networks:
  public:
    driver: bridge
  private:
    driver: bridge

services:
       redis:
        image: redis:7
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
          - "${REDIS_PORT}:6379"
        networks:
          - private
        restart: unless-stopped
        volumes:
          - redis_data:/data
          
      frontend:
        build: ./auth-project
        env_file:
          - ./auth-project/.env
        ports:
          - "3000:3000"
        networks:
          - private
          - public
        restart: always
        depends_on:
          - backend
          - db
        command: sh -c "npx prisma migrate deploy && npm start"
        volumes:
           - .:/app
          - ./prisma:/app/prisma

      backend:
        build: ./cleverSearch
        ports:
          - "5050:5050"
        networks:
          - private
          - public
        env_file:
          - ./cleverSearch/.env
        restart: always
        depends_on:
          - db

     db:
        image: postgres:15
        restart: always
        ports:
          - "5433:5432"
        networks:
          - private
        environment:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: ${DB_NAME}
        volumes:
          - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  redis_data:

