networks:
  public:
    driver: bridge
  private:
    driver: bridge
  pinterest-network:
    external: true

services:
  redis:
    image: redis:7
    command: redis-server --requirepass ${REDIS_PASSWORD}
#    ports:
#      - "${REDIS_PORT}:6379"
    expose:
       - ${REDIS_PORT}
    networks:
      - private
    restart: unless-stopped
    volumes:
      - redis_data:/data

  frontend:
    build: ./pinterest-next
#    ports:
#      - "3001:3000"
    expose:
      - 3000
    env_file:
      - ./pinterest-next/.env
    networks:
      - private
      - public
    volumes:
      - ./pinterest-next:/app
      - /app/node_modules 
      - /app/.next
    restart: always
    depends_on:
      - backend
      - db

  backend:
    build: ./cleverSearch
#    ports:
#      - "5050:5050"
    expose:
      - 5050
    env_file:
      - ./cleverSearch/.env
    networks:
      - private
      - public
    restart: always
    depends_on:
      - db

  db:
    image: pgvector/pgvector:pg15
    restart: always
#    ports:
#      - "5432:5432"
    expose:
      - 5432
    networks:
      - private
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    expose:
      - 80
    networks:
      - private
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  redis_data:
  pgadmin-data:
